### ISSUE TITLE
EasyCamera Android推流地址更改

### ISSUE THREAD

**Issue by xcyl** [EasyDarwin/EasyCamera#1]
以前的推流地址是：rtsp://ip:port/serial/channel.sdp，如rtsp://121.40.50.44:10035/00100100001/1.sdp
现在改为rtsp://ip:port/serial，如rtsp://121.40.50.44:10035/00100100001

**Comment by babosa** [comment]
如果按照EasyDarwin云平台的协议上来说，新的推流地址应该是rtsp://ip:port/serial?channel=[channelID]，但是EasyCamera是一个单通道的设备，默认通道就是1，也就是说，即使后面没有带 ?channel=1，EasyDarwin流媒体服务器端也默认会认为此路推流是channel=1的推流，所以：rtsp://121.40.50.44:10035/00100100001 = rtsp://121.40.50.44:10035/00100100001?channel=1
